### ISSUE TITLE
Unable to locate phpcs

### ISSUE THREAD

**Issue by hajekj** [ikappas/vscode-phpcs#8] opened 2016-05-08 12:45 UTC
Hello,
I tried to install the phpcs plugin for Visual Studio Code but I keep getting `phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.` message. I can access `phpcs` from the Command Line, it is available globally in the `PATH`.
The `PATH` on my device is following:

```
PATH=C:\Program Files (x86)\iis express\PHP\v5.6;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Users\hajek\.dnx\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\hajek\AppData\Roaming\npm
```

I also tried adding `phpcs.bat` to the `PATH` directly, but it didn't change anything (not even after restart). The resulting `PATH` was like this:

```
PATH=C:\Program Files (x86)\iis express\PHP\v5.6;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Users\hajek\.dnx\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\hajek\AppData\Roaming\npm;C:\Program Files (x86)\IIS Express\PHP\v5.6\phpcs.bat
```

I have tried restarting my PC as well, but nothing has changed.

The call to `phpcs` from Command Line is following:

```
C:\Users\hajek>phpcs --version
PHP_CodeSniffer version 2.6.0 (stable) by Squiz (http://www.squiz.net)
```

Running on Windows 10 Pro 1511.

Any idea what I could be doing wrong?

**Comment by ikappas** [comment] 2016-05-19 08:21
Hi @hajekj and thank you for your feedback.

In windows the phpcs is run through a phpcs.bat file that is pre-configured for you when you install phpcs through pear. Otherwise you need to manually create one yourself. Have a look at the installation section in the documentation.

I hope this helps.

**Comment by hajekj** [comment] 2016-05-19 08:24
Hey @ikappas, I have phpcs.bat available in my path. I followed all the installation steps and tried multiple times already.

**Comment by ikappas** [comment] 2016-05-19 08:26
@hajekj Did you install using pear?

**Comment by hajekj** [comment] 2016-05-19 08:28
Yes, it is installed through PEAR.

**Comment by ikappas** [comment] 2016-05-19 08:33
From what I can see from your installation you seem to have phpcs installed under Program Files.
Can you verify that this issue does not occur if you have phpcs.bat on a global path that does not contain spaces? ie C:\php\.

**Comment by hajekj** [comment] 2016-05-19 08:35
I will give it a try and post back once I tested it. If it is so, I believe it should attempt to just execute phpcs.bat in the PATH instead of looking into a folder on C:\ - for example, I am using a PHP which was installed by Web Platform Installer and therefore it is in the C:\Program Files folder

**Comment by mickflaherty** [comment] 2016-06-25 06:03
I have the same issue on the same setup Windows 10, PHP installed through WebPI and VS Code saying I need to add PHPCS to global path.  Did you resolve this?

**Comment by papadi** [comment] 2016-07-18 09:24
Same problem here. PHPCS is installed and works when I run it from the command line, regardless of the current path. VS Code though always gives this error on startup.

**Comment by papadi** [comment] 2016-08-05 15:52
I'm afraid that the error in our case is different and it is suppressed by this code in linter.js
Would it be possible to include the error variable in the output message or some log file?

cp.exec("${phpcsPath} --version", function(error, stdout, stderr) {
    if (error) {
        reject("phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.");
    }
    resolve(new PhpcsLinter(phpcsPath));
});

**Comment by jarandal** [comment] 2016-08-14 04:10
workaround: copy your phpcs.bat to c:\windows

**Comment by hajekj** [comment] 2016-08-14 07:21
It would be great to have a more long term fix rather than copying things into my Windows folder, however thanks @jarandal.

**Comment by MadCoder253** [comment] 2016-09-21 17:16
I want to confirm that the issue is having spaces in the folder path of your project. If you get rid of the spaces then the bug goes away. 

Example: 
My code was located here
c:\users\madcoder253\sources\PHP Repos\tan\website
I got the error of not finding the file.

Then I changed the space to a dash, the error went away and then phpcs extension started to work. 
c:\users\madcoder253\sources\PHP-Repos\tan\website

**Comment by spencerthayer** [comment] 2017-01-08 17:39
@MadCoder253 this however isn't very useful for those of us who cannot change their folder path.

**Comment by MadCoder253** [comment] 2017-01-09 19:35
@spencerthayer Definitely true.

**Comment by MadCoder253** [comment] 2017-01-12 23:34
Thanks ikappas!

**Comment by ikappas** [comment] 2017-01-31 20:32
Hi guys! I have just released 0.7.0 which I tested on Mac OS and Windows incorporating changes with path handling in both the phpcs executable and the linted document. This should fix most of the issues you are experiencing so please let me know if this is the case.

**Comment by ikappas** [comment] 2017-02-23 17:46
I assume that this issue has been resolved in 0.7.0 so closing. Feel free to open a new issue if you do have problems

**Closed by ikappas** 2017-02-23 17:46 UTC
Labels: awaiting feedback

**Comment by spencerthayer** [comment] 2017-02-24 16:39
I installed it just now and received the following error when opening a PHP file.

> phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.

Also please note that "depency" is misspelled.

**Comment by obruehl** [comment] 2017-04-09 07:40
Yes, I confirm this issue.

**Comment by babanesma** [comment] 2017-04-21 11:27
I confirm the issue on ubuntu 16.04 as well as the misspelled "depency"

**Comment by pjpmccarthy** [comment] 2017-05-28 11:10
"I assume that this issue has been resolved in 0.7.0 so closing" Why don't you wait until you get confirmation from someone having the problem. For me it is NOT resolved. I have uninstalled phpcs plugin so that I don't get the annoying error message anymore.

**Comment by Budolfsen** [comment] 2017-05-29 15:26
Not working on Mac OSX even with global install or project based install...
How can we test the 0.8.0 version - to see if it fixes the issue...

**Comment by hajekj** [comment] 2017-05-31 09:24
Hi, I can confirm that for the original case (not working on Windows, this issue is resolved).

**Comment by spencerthayer** [comment] 2017-05-31 18:54
Since this is closed nd @hajekj seems to no longer experience issues I opened a new issue for Mac OS X user. https://github.com/ikappas/vscode-phpcs/issues/48

**Comment by pjpmccarthy** [comment] 2017-06-01 06:40
@hajekj Are you no longer experiencing the issue only because you had to copy something into your protected Windows directory? If so then the issue is not resolved, it has a work-around

**Comment by hajekj** [comment] 2017-06-01 07:11
@pjpmccarthy I installed [PEAR](https://pear.php.net/manual/en/installation.getting.php) and then [Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) through PEAR and it was working out of box. No modifications necessary.

**Comment by pedroskakum** [comment] 2017-06-13 16:48
I have the same problem in linux, the message is:

´´´phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.´´´

**Comment by ejdunn2001** [comment] 2017-06-17 23:57
I am having the same issue.

**Comment by muraliemd** [comment] 2017-08-12 12:02
I am having this issue in windows. Can anyone help me out? 
phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.

**Comment by eddy147** [comment] 2017-08-16 08:22
Same issue, Windows 10.
My path is C:\bin\phpcs\bin
So no spaces.

**Comment by roshimon** [comment] 2017-10-03 04:22
The same annoying **"phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally."**

**Comment by falconxxx** [comment] 2017-10-16 14:53
same issue 👎

**Comment by mhaagens** [comment] 2017-10-25 12:02
Same issue. Globally installed and available in PATH.

**Comment by MohammadShawon** [comment] 2017-10-26 11:19
I have installed PEAR and PHP Codesniffer but still getting error in VSCode.
phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.

**Comment by bryanlopezcodes** [comment] 2017-11-04 01:30
Same problem here

**Comment by Orlegi** [comment] 2017-11-08 19:17
Same issue on MAC OSX. Any advice?

**Comment by SoulFireMage** [comment] 2017-11-09 12:44
This problem still appears in my current version :)

"phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally."

I'm on Windows 10 with the current version of VScode.

**Comment by dwich** [comment] 2017-11-10 23:22
Same problem on Win10, latest, VScode 1.18, phpcs installed using `curl` as mentioned here:
https://github.com/squizlabs/PHP_CodeSniffer
Even though phpcs can be executed on my system in all possible shells without problem, VScode still returns the error message. Those who use git-bash on Windows can use this script "phpcs"

```
#!/bin/sh

script_dirpath=$(dirname $0)
script_dirpath+="/"

php ${script_dirpath}phpcs.phar $@
```

or phpcs.cmd for cmd.exe shell
```
@php "%~dp0phpcs.phar" %* 
```
cmd.exe can see phpcs, git-bash can see phpcs and even built-in terminal in VScode can see phpcs
```
$ phpcs --version
PHP_CodeSniffer version 3.1.1 (stable) by Squiz (http://www.squiz.net)

> phpcs --version
PHP_CodeSniffer version 3.1.1 (stable) by Squiz (http://www.squiz.net)
```

When I open a PHP file in VScode, all I get is the message:
**phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.**

**Comment by ravindragullapalli** [comment] 2017-11-11 01:08
In Ubuntu 16.04, I used PHP Code sniffer from [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) and added **bin** folder to the global path. That removed the message and I started getting suggestions from phpcs.

**Comment by babanesma** [comment] 2017-11-13 08:53
@ravindragullapalli I don't have this issue no more , thank you and thanks everyone

**Comment by hiel** [comment] 2017-12-22 08:55
Just install with Homebrew.
brew install php-code-sniffer

**Comment by irfan88** [comment] 2018-01-02 08:00
same issue on mac elcpaitan. how to resolve?

**Comment by briantully** [comment] 2018-01-03 06:14
so there's no way to get this working on Mac El Capitan? Installed using global composer. phpcs works in Terminal and is in my $PATH, yet VSCode refuses to recognize it. 

Why not update the plugin and allow for the user to manually specify the path to phpcs since it cannot find it intelligently from the $PATH?

"Please add phpcs to your global path or..." <--- what is meant by "global path"? Are you not referring to $PATH? If so, why then won't the following work?

`PATH=$HOME/.composer/vendor/bin:$PATH`

**Comment by jonathanhuet** [comment] 2018-01-04 15:33
As @hiel said, avoid pear installation and use the homebrew installer. Just worked fine for me after going crazy with several ways of modifying the path.

**Comment by briantully** [comment] 2018-01-04 15:38
thanks @jonathanhuet - I did that and it's a good temporary workaround. However I'd rather not have 2 installations of phpcs on my system if possible. I've been bitten by multiple installs of other tools in the past, so would like to avoid that rabbit hole :) 

A setting within the plugin to override/specify the phpcs path would be a reasonable solution, especially since there are already other settings that can be specified for the plugin.

**Comment by hk7507** [comment] 2018-01-05 16:26
windows 10. same issue. If someone find exact solution. Then plz tell me.

**Comment by ejlocop** [comment] 2018-01-18 10:35
same error. im using windows 10 pro

**Comment by mobayen** [comment] 2018-01-18 21:32
This one worked for me:

https://stackoverflow.com/questions/47174009/visual-code-studio-unable-to-locate-phpcs

1- Go to extensions and install the plugin...."phpcs".
2- Search for the extension if you had install it.
3- Disable the extension.

**Comment by briantully** [comment] 2018-01-23 16:06
@mobayen I don't understand. Are you saying disabling the phpcs extension "fixes" the phpcs extension?

I'm still getting the error message even though I added an extra install of phpcs via homebrew. The problem is that I now have 2 installs of phpcs, one in my ~/.composer/vendor/bin (Composer installed) and one in /usr/local/bin (Homebrew installed). The Composer installed phpcs has priority and also has all my extra/custom coding standards.

So homebrew install doesn't work if you already have a composer install of phpcs.

**Comment by AndreasHeintze** [comment] 2018-01-31 13:50
I have the same problem. Running VS Code on a MacBook Pro. Please fix this.

**Comment by mobayen** [comment] 2018-02-22 17:24
@briantully  
I really don't know how or why this works but yes.
I installed and uninstalled that extension and then my problem solved

**Comment by kestonorherhe** [comment] 2018-03-04 04:47
Read the plugin details on instructions to install dependencies using composer, a line of code is given to run, run it to download all needed dependencies if you already have composer installed else install composer and run code. Once done, restart VScode.
This worked for me just now, lemme know if it worked for you as well.

**Comment by hulkur** [comment] 2018-05-01 08:21
MacOS 10.13.4, Code 1.22.2, PHP_CodeSniffer 3.2.3

It gives correct command line in error message, so it knows where to look, but still gives error.
If I copy command line from error message and run it in terminal then it works fine.

**Comment by HaniAmmar** [comment] 2018-05-11 01:13
if I set 
phpcs.executablePath to php  c:/phpcs/phpcs

it adds the project folder to it, however, if I give it absolute path, it adds quotation marks and end up looking like this (note quotation): 

"c:/php/php.exe c:/phpcs/phpcs" --version

it should be this: "c:/php/php.exe" "c:/phpcs/phpcs" --version

or just: c:/php/php.exe c:/phpcs/phpcs --version

I think it something about detecting a space and wrapping the path with ""

**Comment by HaniAmmar** [comment] 2018-05-11 01:25
in linter.ts:
let result: Buffer = cp.execSync(`"${executablePath}" --version`);

to

let result: Buffer = cp.execSync(`${executablePath} --version`);

after that, you can set it to something like this:
    "phpcs.executablePath": "\"c:/php7/php.exe\" \"c:/PHP_CodeSniffer/bin/phpcs\""

**Comment by donkovah** [comment] 2018-05-22 15:43
The Documentation says you should install PHPCS globally via Composer.
"composer global require squizlabs/php_codesniffer" should do the trick

**Comment by rbrisita** [comment] 2018-09-10 16:17
In my case, it didn't.

**Comment by AmirHosseinKarimi** [comment] 2018-09-13 19:03
I have same issuse on Debian 9

**Comment by DavyGuedes** [comment] 2019-01-28 21:51
I have same issue on Manjaro 18.0.2

**Comment by azbatuk** [comment] 2019-03-30 06:22
I was having the same problem, and placing the phpcs.bat's folder (it is in /Users/johndoe/AppData/Roaming/Composer/vendor/bin) in system path did not help it.

Then I tried to enter "phpcs.executablePath" : "/Users/johndoe/AppData/Roaming/Composer/vendor/bin/phpcs.bat" into VS Code's settings.json and it worked.
As you can see I had to add the file name to the folder path to make it work. It is not accidental, it does not work if you do not have "phpcs.bat" in the path.

Windows 10
VS Code 1.32.3
