### ISSUE TITLE
error: "phpcs: Unexpected token F in JSON at position 0"

### ISSUE THREAD

**Issue by polyamide** [ikappas/vscode-phpcs#32] opened 2017-02-06 03:27 UTC
I got this error "phpcs: Unexpected token F in JSON at position 0" every time I open or save a PHP file.

My phpcs is installed system-wide, and it is working properly in my terminal.

```
$  php --version
PHP 5.6.29 (cli) (built: Jan 14 2017 21:05:20)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

$  which php
/usr/local/php5/bin/php

$  phpcs --version
PHP_CodeSniffer version 2.6.2 (stable) by Squiz (http://www.squiz.net)
```

My guess is that this extension is parsing the text report (not a JSON format report) by mistake. The error message `Unexpected token F in JSON` looks like the first character of this:

```
$ phpcs src

FILE: test.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 8 | ERROR | [x] Whitespace found at end of line
```

**Comment by mvdriel** [comment] 2017-02-21 22:25
Any idea when version 0.8.0 will be released? This issue seems pretty critical to me.

**Comment by ikappas** [comment] 2017-02-23 17:36
@mvdriel I have not fully tested 0.8.0 and I am pretty swamped with a project atm. So I can't really say how soon I can release it. 

Meanwhile you can easily clone this repo and build the plugin using the development branch and report any bugs 👍

**Comment by wilsmex** [comment] 2017-04-18 02:26
Same thing here.  Terminal works fine: "phpcs: Unexpected token P in JSON at position 0" in VSCode when trying to change any of the config settings such as "phpcs.standard".

**Comment by frekel** [comment] 2017-05-15 07:18
Can I bump this issue a bit? I really would like 0.8.0 released!

Thanks,
Frank

**Comment by robindrost** [comment] 2017-05-26 12:29
Cannot use the plugin anymore. Constantly getting the error Unexpected token F in JSON at position 0.

**Comment by yegorLitvinov** [comment] 2017-05-31 12:23
try to install php-xml

**Comment by yegorLitvinov** [comment] 2017-05-31 12:23
try to install php-xml

**Comment by frekel** [comment] 2017-05-31 14:10
php-xml is installed, but the error keeps popping up :(

**Comment by Nomafin** [comment] 2017-06-02 08:16
We solved this problem on my co-worker's computer so that we uninstalled the PHPCS that was installed with homebrew and used [this](https://github.com/squizlabs/php_codesniffer) one instead.

**Comment by srikat** [comment] 2017-06-10 12:03
Not sure if this is related - in my case this is the error:

phpcs: Unexpected token ' in JSON at position 0

**Comment by rezashamdani** [comment] 2017-06-17 07:19
same problem to me.
the console seem having no problem running phpcs/phpcbf, yet the one inside visualstudiocode is always throw this kind of error.
sadly i have to disable this plugin in vscode until it being fixed, but i still using it on console.

@Nomafin  i've tried your suggestion, yet still not work. thanks

**Comment by Ceelog** [comment] 2017-06-18 07:41
I also found this problem but I fix it in follow way:

- Environment
Windows 7 / vscode 1.13.1

- fix

try to execute following commend in your system
```
php phpcs.phar -q --standard=PSR2 /path/to/file.php --report=json
```

the only expected output should be a json object but ***without any other php notice/warnning/error***

if you get any other  php notice/warnning/error, you should change error_reporting setting in php.ini

gooooooood luck ;)

**Comment by rezashamdani** [comment] 2017-06-26 02:02
notice the error location by showing off the Toggle Developer Tools;
<img width="893" alt="screen shot 2017-06-26 at 8 59 29 am" src="https://user-images.githubusercontent.com/3622787/27522157-0645e7ea-5a4e-11e7-815c-e8638a244850.png">

**Comment by davisshaver** [comment] 2017-06-27 13:11
I am having this problem too.

**Comment by inthedeepend** [comment] 2017-07-04 00:19
I'm getting 'phpcs: Unexpected token N in JSON at position 0'

**Comment by mauryaratan** [comment] 2017-07-05 07:44
In my case, removing `<arg value="psvn"/>` from ruleset fixed the issue for me.

**Comment by McPan68** [comment] 2017-07-08 07:10
I'm getting 'phpcs: Unexpected token M in JSON at position 0'

**Environment:**
Windows 7 x64 / vscode 1.13.1 / PHP_CodeSniffer version 2.8.0 (stable)

Error just pops up when switching from php 5.6 to php 7.1. I'm using following wrapper batch file for phpcs call
`C:\devel\php56\php.exe "C:\bin\phpcs.phar" %*`
When I'm using the php 5.6 interpreter for phpcs, there's no error, when using php 7.0 or 7.1 error will pop up.

**Comment by mmoore247** [comment] 2017-07-13 21:32
Hi,

I am getting the error below when attempting to "Start Debug".

phpcs: Unexpected token C in JSON at position 0

**Environment**:

Ubuntu 17.04 / vscode 1.14.0

PHP PHP 7.0.18

If anyone could offer any insight on how to resolve this it would be greatly appreciated.

If there is any additional information I could provide to help narrow down the cause of the error please let me know.

Thanks!
Michael

**Comment by McPan68** [comment] 2017-07-15 06:20
Hi,
as a test I would suggest to create a php file named `empty.php` i.e., which is containing just the php opening tag `<?php`. Nothing else, no whitespaces, no linefeed. Run this file on a command line with `php -f empty.php` and check if there is any output. As expected there should be no output at all. If there is still any output, maybe any warnings or error messages, I think this is the reason for your unexpected token error.

**Comment by Paladin** [comment] 2017-07-19 20:55
Just a heads-up. The fix in here (adding "-q" to the phpcs command) breaks with older versions of phpcs that don't have a -q option available. Might want to turn it into a config option?

**Comment by mmoore247** [comment] 2017-07-21 17:05
Hey Guys,

I appreciate the responses! I switched my work machine to Arch and I am no longer having any issues. I am sure my issue was likely user error.

For what it is worth I did try Paladins suggestion prior to posting my original message and I should have mentioned that.

Thanks again,
Michael

**Comment by chualuoi** [comment] 2017-07-22 03:03
Just had the same issue and fixed it. I think this issue happen when you use phpcs 3.0. If I switch back to phpcs 2.9.1 then everything works fine.

**Comment by chualuoi** [comment] 2017-07-24 06:53
1 more update, I set up another machine recently and discover that If you're using [Wordpress coding standard](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), upgrading it may cause an issue as well.

**Comment by jimrubenstein** [comment] 2017-07-28 02:19
Having the same issue here (`phpcs: Unexpected token P in JSON at position 0`).

Was running PHPCS version 3.0.1

Per @chualuoi's suggestion, downgraded to 2.9.1.

Can confirm, no longer getting the issue.

If you have phpcs installed globally via composer, you can downgrade like this:

`composer global require 'squizlabs/php_codesniffer:~2.0` 

that will give you the newest version of the 2.0 line available.

**Comment by McPan68** [comment] 2017-07-28 15:20
Just switched from phpcs 2.8.0 to current 3.0.2 (vscode 1.14.2). Can't confirm any "unexpected token" errors yet.

**Comment by jimrubenstein** [comment] 2017-07-28 15:33
I feel like the error is coming from either phpcs, or an unexpected message
passed from phpcs back to the extension.

I'm not sure how to get in and debug the exact same phpcs command or the
returned message myself, otherwise I would.

The developer tools look like they pick up in the vscode worker, where the
extension is notifying vscode to display an error...which is well
after/away from where the error is actually happening.

**Comment by shrop** [comment] 2017-07-31 02:14
I have phpcs and Drupal Coder installed via global composer. I was able to get things working by setting Drupal Coding Standards like this: `"phpcs.standard": "Drupal,DrupalPractice"`. I did receive the JSON parse error mentioned when using an absolute path to the Drupal coding standard folder.

**Comment by bfodeke** [comment] 2017-08-01 15:40
Confirmed that @shrop's fix worked for me

**Comment by rezashamdani** [comment] 2017-08-08 05:08
Updated the phpcs to `PHP_CodeSniffer version 3.0.2 (stable) by Squiz (http://www.squiz.net)`
Using both latest VS & VS Insider, still failed with error `phpcs: Unexpected token  in JSON at position 0`

any workaround for this issue?

**Comment by Paladin** [comment] 2017-08-08 16:00
The patch referenced earlier (basically changing phpcs-server/src/linter.ts so there's a "-q" in the command) works, so long as you're always going to be using a recent version of phpcs. The "-q"hasn't always been a valid option for phpcs, so it will crash if using an early enough version of phpcs (I *think* it fails on all 1.x but 2.x and higher may work...haven't done the detailed tracking to be sure precisely where the break point is).

**Comment by gnowland** [comment] 2017-08-14 17:56
Thanks @Nomafin, after a couple hours of head banging it turns out it was indeed the homebrew version of PHPCS that was causing the "`phpcs: Unexpected token P in JSON at position 0`" issue!! Running `brew uninstall php-code-sniffer` and subsequently `pear install PHP_CodeSniffer` completely solved it.

**Comment by iamanders** [comment] 2017-08-17 08:13
Was having the same problem. But managed to solve it by downloading the latest version of Wordpress rulesets.

**Comment by m4agenbitter** [comment] 2017-08-19 20:12
I just started using phpcs and got the same error.
I could fix it by setting my coding standard on the command line and also got a lot of PHP notices, maybe not related though.
(I'm using Windows) 
```
F:\php>phpcs --config-set default_standard PSR2
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
PHP Notice:  Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604

Notice: Undefined variable: phpCodeSnifferConfig in F:\pear\pear\PHP\CodeSniffer\src\Config.php on line 1604
Config value "default_standard" added successfully
```

It worked flawlessly the second time:
```
F:\php>phpcs --config-set default_standard PSR2
Config value "default_standard" updated successfully; old value was "PSR2"
```
This don't really sounds like a real fix to me, however it worked (somehow).

**Comment by urre** [comment] 2017-08-23 11:53
I solved this by installing 2.9 instead of 3.0. Installed phpcs from Composer.

**Comment by AustinWinstanley** [comment] 2017-08-27 23:30
**Workaround (Ubuntu 17.04/Composer)**

{
	"name": "",
	"description": "",
	"type": "",
	"license": "",
	"require": {},
	"require-dev": {
		"dealerdirect/phpcodesniffer-composer-installer": "0.4.0",
		"squizlabs/php_codesniffer": "2.9.1",
		"wp-coding-standards/wpcs": "*"
	}
}

**Comment by virusvn** [comment] 2017-09-01 02:37
I met this problem and here my solution:
At first, check phpcs (via composer) at the src folder, ex: "./vendor/bin/phpcs src", when I ran this command, I realized that my installed_path is incorrect, that's why it's displayed errors.
"phpcs: Unexpected token P in JSON at position 0" => because the result of above command "PHP Fatal error: ..."
"phpcs: Unexpected token F in JSON at position 0" => because the result of above command "Fatal error: Uncaught: ..."

By default, this plugin will use phpcs via composer over phpcs of system. This is already noted.

My composer.json:
{
"require-dev": {
        "cakephp/cakephp-codesniffer": "3.*",
        "squizlabs/php_codesniffer": "^3.0"
}
}

**Comment by setokaibakg** [comment] 2017-09-08 14:57
homebrew and older php-code-sniffer rulesets aren't friends. I was trying to use drupal-code-sniffer.

I had to do the following to get it to work on a Mac.
brew install php-code-sniffer
brew install drupal-code-sniffer (which installs php-code-sniffer 3.0.2 as req)
brew install php-code-sniffer@2.9
which phpcs (get location installed or look at install info)
copy /usr/local/Cellar/php-code-sniffer@2.9/2.9.1 folder to /usr/local/Cellar/php-code-sniffer/
brew switch php-code-sniffer 2.9.1

the Drupal ruleset I needed is working. (I know other people were suggesting composer but I didn't want to deal with path issues right now)

**Comment by thanh-taro** [comment] 2017-09-14 06:57
I got the same issue and don't know how to fix it. But I think this plugin is using JSON format for report (`--report=json`) and it includes the log of phpcs (`...E...W...EEE........`) so when plugin read report, it failed and give us `phpcs: Unexpected token . in JSON at position 0` (the first letter of log)

**Comment by thanh-taro** [comment] 2017-09-14 07:31
I found a solution. Just add <arg value="q"/> to your rule standard (ex: `ruleset.xml`) and the problem solved.

**Comment by dingo-d** [comment] 2017-10-07 18:42
I am on MacOS HighSierra, and I have coding standards installed (I am using WordPress coding standards) in a folder called `wpcs` in my home directory. When i type `phpcs -i` in the terminal I get all the standards installed.

When I try to set the standard in visual code like

```
"phpcs.standard": "~/wpcs/WordPress/ruleset.xml"
```

> phpcs: Unexpected token P in JSON at position 0

I tried with 

```
"phpcs.standard": "WordPress"
```

Which gives me this error:

> phpcs: The "WordPress" coding standard set in your configuration is not installed. Please review your configuration an try again.

Is there a workaround for this?

**Comment by thanh-taro** [comment] 2017-10-08 09:47
@dingo-d You may need to add `<arg value="q"/>` to your xml rule set or use `-q` option on command.

**Comment by dingo-d** [comment] 2017-10-08 13:04
@thanh-taro But this is the default WordPress standard...

**Comment by dheerajwebkul** [comment] 2017-10-12 16:18
OS: ubuntu 14.04
VSCode: 1.17.0
phpcs extention in vscode: Version : 0.7.0 https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs  

Everything was fine in the last vs code version But after just updating to vs code new v 1.17, I got this warning everytime open and save a PHP. 

Is any idea to just hide this warning, if there is no solution to fix this for now?
It's very annoying.

Thanks,

**Comment by Paladin** [comment] 2017-10-17 18:09
Look up at the top of the thread. There's a commit entitled "Suppress non-JSON output" -- read it and make that change in your installed plugin.

It changes one line in the linter.js file (something like line 227 in the javascript file, I believe). That patch works around the error. Owner's just been too busy to package and ship it. (Or has decided to try and build a better fix, such as accepting the default output from phpcs and extract the JSON from it. That would avoid the "gotcha" from the next paragraph. No idea which is the case, currently, but he cited lack of time earlier.)

The only "gotcha" condition on it is if you're using an old copy of phpcs. Early versions of it break because they don't accept the "quiet" option (nutshell: it's outputting text by default, not pure JSON). I think the patch works with every version since 2.0, though, so you're probably not going to see it often.

**Comment by aymone** [comment] 2017-10-17 20:32
<arg value="q"/> resolved this for me.

**Comment by Paladin** [comment] 2017-10-17 21:42
True, and in many circumstances that's a simpler approach. But sometimes you're sharing codebases with lots of other people, not all of whom care about special settings needed just for vscode (and some of whom may *want* the extra text that arg  stops). So it (phpcs.xml) becomes something extra for you to add to and keep track of for every project you work on. That kind of thing bugs me, but I admit that's a personal foible.

Whether you modify the linter.js file, making a change once for all the codebases you work in, or set up a separate file that you copy separately is a decision left to personal circumstances. (In my own case, a lot of the folks I work with use phpstorm, which avoids this issue and I have my fingers in many shared codebases, using different versions of phpcs, so I took the patch route because I can do it once and reliably have it to hand every time I open vscode, whatever codebase I'm in. Like everything else, there's more than one way to fix this.)

**Comment by mbirth** [comment] 2017-10-18 14:14
FYI: In Windows I have the error

> phpcs: Unexpected token ' in JSON at position 0

And the problem seems to be that I opened a folder/file from a network share. The message returning from the phpcs call is:

```
'\\somehost\d$\htdocs\somefolder'
CMD.EXE was started with the above path as the currect directory.
UNC paths are not supported. Defaulting to Windows directory.
{"totals":{"errors":2,"....
```

When mapping that UNC to a drive letter and opening the project from that new "drive", phpcs works fine.

Maybe there should be code added to the `linter.ts` to filter out the error message (as the results are still there) or start cmd.exe from a local directory.

**Comment by ikappas** [comment] 2017-10-27 23:16
Hi everyone and thank you for your patience! 

A lot of these issues come from errors occurring during phpcs execution such as PHP Notices, PHP Fatal Exceptions, Other Script Output, etc, most of which can be detected as follows:

Execute the phpcs command with --report=json and see whether the output contains anything other than json that would cause the extension to fail!

It has also come to my attention that some rulesets such ie. `Infinum` include overrides to default report configuration which causes phpcs to output both json and full report at the same time. This looks like a bug for PHP_CodeSniffer. 

Last, but not least, If someone has a good idea on how to improve `linter.ts` error filtering I am open to suggestions!

Updated code has been pushed to the development branch preparing a 1.0.0 release. So have a look and help debug your issues to create a stable release!

**Comment by ikappas** [comment] 2017-10-27 23:19
@mbirth Have a look at https://support.microsoft.com/en-us/help/156276/cmd-exe-does-not-support-unc-names-as-the-current-directory

**Comment by ikappas** [comment] 2017-10-27 23:24
Regarding the -q option :

1. -q (quiet) option is available since phpcs 2.6.2
2. It has been implemented in the development branch for quite a while... just not published!

**Comment by dingo-d** [comment] 2017-10-28 07:37
> It has also come to my attention that some rulesets such ie. Infinum include overrides to default report configuration which causes phpcs to output both json and full report at the same time. This looks like a bug for PHP_CodeSniffer.

We have full report set as default in our coding standards, so that should override any other output (unless you are trying to force the json at all times). Also I tried with the default standards, and couldn't get it to work properly. 
When looking at the default sniffs, they don't seem to force any special report type.

**Comment by azbatuk** [comment] 2017-10-29 06:37
I was having this same problem. My error message was "phpcs: Unexpected token X in JSON at position 0".

Ubuntu 16.04 LTS, PHP7.1, VS Code 1.17.2, PHPCS 0.7.0

I followed McPan68's suggestion to troubleshoot it. I created a php file (empty.php) which contained only the php opening tag <?php. Nothing else. Then I ran this file on a command line with "php -f empty.php" and I received "XDebug could not open the remote debug file '/var/log/xdebug/xdebug.log'." error message. It turns out Xdebug was having an issue and that "X" in phpcs error message is clearly the "X" of Xdebug. Once I disabled the Xdebug the annoying error disappeared.

So, it seems if you are receiving this error your PHP is doing something which is creating phpcs related error.

**Comment by mbirth** [comment] 2017-11-01 10:24
@ikappas I finally got the chance to test that registry setting. But now the error changed to:

> phpcs: The file "\d$\htdocs\somedirectory\somefile.php" does not exist.

(The folder opened in VSCode was `\\someserver\d$\htdocs\somedirectory`.)

**Comment by ikappas** [comment] 2017-11-01 23:28
I just pushed some major new features in `develop` branch that need testing and include: 

- ability to set phpcs.executablePath
- ability to set phpcs.showWarnings 
- ability to set phpcs.showSources 
- ability to enable phpcs.trace.server with messages or verbose option for tracing errors.
- ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json

Your feedback is very welcome!

**Comment by markoshust** [comment] 2017-11-16 16:50
I can confirm this error was being caused from the `<arg value="np" />` line from `phpcs.xml`. This is a standard phpcs.xml definition, so this is still a valid issue.

**Comment by ethanteague** [comment] 2017-11-23 14:36
phpcs and plugins work with PhpStorm, Emacs, et. al. Something is wrong with this plugin.

**Comment by McPan68** [comment] 2017-11-23 16:12
@ethanteague: I wouldn't usually leave it like that. I am using phpcs 3.0.2 with vscode 1.18.1 (x32) and php 5.6-7.1 without any of the problems described above.

**Comment by frekel** [comment] 2017-11-29 08:52
@ikappas: I would love to give you feedback but still haven't a clue on howto install the plugin outside visual studio code....

**Comment by gusbemacbe** [comment] 2017-12-03 21:58
# Mac users, be careful to install Pear if you upgrade to PHP 7.2!

Check my issue:
https://github.com/Homebrew/homebrew-php/issues/4623#issuecomment-348816979

If you want to make `phpcs` working, risk to install Pear and follow Javian's instrucitons:

https://github.com/Homebrew/homebrew-php/issues/4623#issuecomment-348816979

**Comment by gusbemacbe** [comment] 2017-12-03 22:11
If you are an user of macOS High Sierra and use PHP 7.2, do not want to risk with Pear and to damage your PHP folder, follow the instructions of @setokaibakg. His instructions are safe.

**Comment by LittleHamster** [comment] 2017-12-09 16:29
@ikappas 
any updates about this?

**Comment by young666** [comment] 2018-01-03 16:40
I'm using XAMPP, in php.ini, I turn off php_openssl module by editting to ;extension=php_openssl.dll. Then the issue solved :)

**Comment by sami9gag** [comment] 2018-01-04 02:17
While this isn't an issue with the extension itself, the error should be made more obvious. Currently the error message shown doesn't give a casual user a good idea of where to start with resolving the error.

**Comment by anibalsanchez** [comment] 2018-01-04 14:40
<arg value="q"/> solved the issue on PHPCS 2.9.1

**Comment by LittleHamster** [comment] 2018-01-04 18:29
@anibalsanchez 
I have the latest PHPCS and still have this issue: 
![image](https://user-images.githubusercontent.com/10330481/34578498-38b5fbec-f153-11e7-84a7-993019a649d7.png)

**Comment by anibalsanchez** [comment] 2018-01-04 19:11
The problem of this issue is that the --report=json option generates an invalid json. It includes a progress output with a letter like E or F before the json structure.

So, the `<arg value="q"/>` in the ruleset does the trick to hide the letter.

@LittleHamster Your issue doesn't seem to be the same issue.

**Comment by thierrymichel** [comment] 2018-01-16 08:26
Solved updating WP rulesets as mentioned by @iamanders (https://github.com/ikappas/vscode-phpcs/issues/32#issuecomment-323000631).

**Comment by di3663** [comment] 2018-01-27 12:48
try add '@'
```
@%~dp0php.exe -c %~dp0php.ini %~dp0phpcs.phar %*
```
on windows

**Comment by SharakPL** [comment] 2018-01-31 12:38
Got the same problem today. I mean:
> phpcs: Unexpected token ' in JSON at position 0
And it seems the problem is that lintered file is too big. I get this error when viewing php files over 1MB size. With other files phpcs works perfectly fine. Maybe it's VSCode's setting that needs to be changed or phpcs has limits on file size

**Comment by dingo-d** [comment] 2018-01-31 13:17
If the file is too big you'll run out of memory (allowed memory size exceeded error). This is not related to the linter or the editor, but to the phpcs (or rather php).

**Comment by ikappas** [comment] 2018-02-17 00:58
I just pushed multi-root support in develop branch that needs testing

**Comment by ikappas** [comment] 2018-02-20 12:33
I've just pushed 1.0.0-beta.6 on the development branch adding automatic configuration search. This is the last feature for the 1.0.0 release which needs some testing before 1.0.0 launch.

**Comment by ikappas** [comment] 2018-02-21 10:49
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.

**Closed by ikappas** 2018-02-21 10:49 UTC
Labels: awaiting feedback, bug

**Comment by gusbemacbe** [comment] 2018-02-21 19:50
Chaírete, @ikappas, does `ability to set phpcs.showWarnings` ignore some certain warning I do not want to see and to correct in my PHP files? It is boring your package classifies everything as wrong and also classifies my favourite Allman brackets as wrong. Eucharistó polý!

**Comment by ikappas** [comment] 2018-02-21 22:36
@gusbemacbe you can fiddle with `phpcs.warningSeverity` as descripted in https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#filtering-errors-and-warnings-based-on-severity

**Comment by LittleHamster** [comment] 2018-02-21 23:05
@ikappas 
thanks for the update 👍 

I am getting this error, the error is so long that I can't see the rest of it

![image](https://user-images.githubusercontent.com/10330481/36510668-d68de272-1731-11e8-9f32-e756b6c5329d.png)
