### ISSUE TITLE
Unable to locate phpcs

### ISSUE THREAD

**Issue by spencerthayer** [ikappas/vscode-phpcs#48] opened 2017-05-31 18:53 UTC
Issue #8 was closed and @hajekj reports that the issue is fixed for Windows. However, this is not the case for OS X. Please see comments below https://github.com/ikappas/vscode-phpcs/issues/8#issuecomment-282338771 .

**Comment by Budolfsen** [comment] 2017-06-09 09:03
I can confirm that it is not working on OS X

**Comment by naknak987** [comment] 2017-07-11 19:20
I can't get it working in windows though.

**Comment by msonowal** [comment] 2017-07-15 06:27
me to macOS Sierra phpcs is installed globally via composer it terminal I can get output of phpcs i.e. PATH is present in environment but still now working

**Comment by auz1111** [comment] 2017-10-10 17:39
**phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally**

Still occurring on OS X.

**Comment by hzb** [comment] 2017-10-29 14:16
@auz1111 me too, `phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.` still occurring on macOS.

OS: macOS High Serria
Version: 10.13.1 beta(17B46a)
VSCode version: 1.17.2

**Comment by ikappas** [comment] 2017-10-29 15:00
@auz1111 Which version of the extension are you using? The marketplace one or the development one?

**Comment by rob-gordon** [comment] 2017-10-31 13:44
Also having this problem on Sierra with the marketplace extension.

**Comment by ikappas** [comment] 2017-11-03 08:32
This issue should be resolved in latest develop branch so please consider testing your use cases.

**Comment by caramelomartins** [comment] 2017-11-17 10:38
@ikappas I'm using Ubuntu 16.04 and I can confirm that I was able to go around this issue with version `1.0.0-beta.4`. My use cases worked and I was able to see warnings from `phpcs`and fix files. I still had to set the full path to my `phpcs` global alias, was that what you intended?

**Comment by Wrenbjor** [comment] 2017-12-27 14:24
Hello @ikappas, I am very new to using VSCode, are there instructions to installing/switching to the development branch of a plug-in so that I can test?

**Comment by lntmny** [comment] 2018-01-23 08:43
https://github.com/ikappas/vscode-phpcs/blob/f18e40713bae56316c768b2d1c44112f13350342/phpcs-server/src/linter.ts#L40

For windows, all extnames in env `%PATHEXT%` can be supported, not only .bat.

**Comment by caramelomartins** [comment] 2018-01-24 00:00
@Wrenbjor Hey, you can see some instruction on running the development branch of vscode-phpcs [here](https://github.com/ikappas/vscode-phpcs#rundebug-development-version) in the README of this repo.

**Comment by jeevad** [comment] 2018-02-12 10:59
cmd run as admin and type following command

`pear install PHP_CodeSniffer`

**Comment by ikappas** [comment] 2018-02-21 10:52
I just released vscode-phpcs 1.0.0 which supports the VSCode 1.20+ and includes many enhancements most notable of which are:

1. multi root support
2. lint as you type support
3. automatic configuration search support
4. ability to set phpcs.executablePath
5. ability to set phpcs.showWarnings
7. ability to set phpcs.showSources
8. ability to set phpcs.composerJsonPath to something other that workspaceRoot/composer.json
9. ability to enable phpcs.trace.server with messages or verbose option for tracing errors.

I would like to give my thanks to all the people that helped track down issues in the previous betas and hope the new features help you get things done easier.

On that note, I am closing this issue to properly track any new issues in the new release. If you find this issue persists or any other issue please feel free to open a new ticket for v.1.0.0.

**Closed by ikappas** 2018-02-21 10:52 UTC
