### ISSUE TITLE
spaces or indentation not detected

### ISSUE THREAD

**Issue by YanweiJiang** [ikappas/vscode-phpcs#31] opened 2017-02-06 00:41 UTC
Using php standard PSR2:
when indented 2 spaces, it will complain and lint correctly;
when indented 6 or more spaces or multiple tabs, it will not complain and ignore

**Comment by ikappas** [comment] 2017-02-11 17:18
@YanweiJiang  can you please provide me with a sample php file that has this behaviour?

**Comment by YanweiJiang** [comment] 2017-02-12 06:40
`<?php

if ($vars['page_type'] == 'home') {
    echo elgg_view('page/elements/home_page/header', $vars);
} else {
    echo elgg_view('page/elements/header_inner', $vars);
}
`

**Comment by YanweiJiang** [comment] 2017-02-12 06:43
[header.txt](https://github.com/ikappas/vscode-phpcs/files/769128/header.txt)

**Comment by ikappas** [comment] 2017-02-13 08:35
@YanweiJiang I can confirm that this is happening and feels like a phpcs bug so I opened a bug here https://github.com/squizlabs/PHP_CodeSniffer/issues/1345

**Comment by YanweiJiang** [comment] 2017-02-13 09:22
agree. I tried in Sublime 3, it has the same issue.

**Comment by ikappas** [comment] 2017-02-13 10:51
@YanweiJiang According to https://github.com/squizlabs/PHP_CodeSniffer/issues/1345 this is intended behavior so I am closing this issue.

If you wish to apply more strict rules the following ruleset.xml configuration works the way you want:
```xml
<rule ref="Generic.WhiteSpace.ScopeIndent">
    <properties>
        <property name="exact" value="true" />
    </properties>
</rule>
```
See relevant https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericwhitespacescopeindent

**Closed by ikappas** 2017-02-13 10:51 UTC
Labels: phpcs related

**Comment by YanweiJiang** [comment] 2017-02-13 20:09
Cool. Thank you
