### ISSUE TITLE
phpcs: Request workspace/configuration failed with message: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by mishac** [ikappas/vscode-phpcs#90] opened 2018-02-21 13:49 UTC
When I try to run the newest version that just installed (1.0.1), I get the following error:

phpcs: Request workspace/configuration failed with message: Cannot read property 'uri' of undefined

**Comment by ikappas** [comment] 2018-02-21 14:06
@mishac Thank you for reporting this issue. Can you please provide your vscode configuration?

**Comment by mishac** [comment] 2018-02-21 14:09
I'm 100% not sure what you're asking for exactly.

in my usersettings I have:

        "phpcs.standard": "Drupal"

and workspace settings are empty.

All other settings are set to the default.

Things worked fine until the update, though I was getting the "phpcs: Unexpected token" json errors periodically before.

And here's my phpcs version:

    phpcs --version
    PHP_CodeSniffer version 2.9.1 (stable) by Squiz (http://www.squiz.net)

**Comment by ikappas** [comment] 2018-02-21 14:23
@mishac By default the workspace settings should not empty, they should be like:
```json
{
	"folders": [
		{
			"path": "/path/to/your/project"
		}
	],
	"settings": {}
}
```

I managed to reproduce this issue by opening a new VSCode window and adding a folder to workspace and then manually deleting workspace settings.

What are the exact steps that you do to reproduce this for your use-case?

**Comment by mishac** [comment] 2018-02-21 14:26
I literally just updated the extension, restarted vscode, and went to file->open to open a PHP File.   I don't have a currently open project, which is why the workspace settings are emtpy.

**Comment by mishac** [comment] 2018-02-21 14:26
I literally just updated the extension, restarted vscode, and went to
file->open to open a PHP File.   I don't have a currently open project,
which is why the workspace settings are emtpy.

**Comment by ErikFontanel** [comment] 2018-02-21 17:42
I encountered this too, removing `settings.json` from `${workspaceFolder}.vscode` fixed it

**Comment by Blfrg** [comment] 2018-02-21 18:58
I'm also experiencing this issue since updating to v1.0.1

I looked into `settings.json` since it was being referenced here.
The issue seems to happen if you have more than 1 folder in the project.
```
{
	"folders": [
		{
			"path": "/path/to/your/project"
		},
		{
			"path": "/path/to/other/folder"
		}
	],
	"settings": {}
}
```
I confirmed by:

1. removing the 2nd path from the file
2. reload window
3. no error when viewing file
4. added the 2nd folder back into the file
5. reload window
6. error returns

The error is seen regardless if the file is from the 1st or 2nd folder.
I also tried combinations of relative/absolute paths but still resulted in errors when multiple paths were present.

**Comment by sveggiani** [comment] 2018-02-21 20:32
I'm getting this too, but only on diff views of PHP files

**Comment by ikappas** [comment] 2018-02-21 22:25
@mishac @ErikFontanel @Blfrg @sveggiani Thank you all for reporting this issue. I've just released 1.0.2 with a fix.

**Comment by Blfrg** [comment] 2018-02-21 22:50
@ikappas Thank you for the quick turn around, this appears resolved for me!

**Comment by ikappas** [comment] 2018-02-22 09:41
Closing this as fixed. Feel free to reopen if you still have issues!

**Closed by ikappas** 2018-02-22 09:41 UTC
Labels: bug
